### ISSUE TITLE
Домашнє завдання №1 (2018/01/28)

### ISSUE THREAD

**Issue by dmytro** [pavloolenchyk/training#1]
- Повторити використання, вміти вживати і вміти пояснити команди:
   - `git init`
  - `git add`
  - `git commit`
- Вміти створити новий репозиторій у `git` та `github`
  - Створити репозиторій `home-work-20180128`
  - Додати до репозиторію файл `README.txt` із списком використаних для цього команд
- Описати процес в коментарі до цього завдання

**Comment by pavloolenchyk** [comment]
![screenshot_15](https://user-images.githubusercontent.com/34408189/35762326-539a8616-08d8-11e8-9ed2-0580a6625c98.png)
![screenshot_16](https://user-images.githubusercontent.com/34408189/35762353-93adb886-08d8-11e8-8d85-2022bc9908ae.png)
Перше було fatal: Authentication failed, з яким я зробив що було потрібно із оцієї сторінки:
![screenshot_17](https://user-images.githubusercontent.com/34408189/35762383-fb592e66-08d8-11e8-9b51-15499db863dd.png) а тоді уже видає fatal: 'origin' does not qappear to be a git repository і fatal: Could not read from remote repository.

**Comment by pavloolenchyk** [comment]
знову fatal" Authentication failed

**Comment by dmytro** [comment]
Ці повідомлення означають, що remote репозиторій під назвою test не існує.
Тобто, перш ніж надсилати коміти в віддалений репозиторій, треба щоб він
існував.

Віддалений репозиторій має такі 2 важливі характеристики:
- назва (або alias) -- наприклад origin
- URL (адреса в інтернеті) -- https://github.... і так далі

Тобто, треба додати remote той репозиторій, який вже створений на github.

  *Dmytro Kovalov*
  http://dmytro.github.io


2018-02-03 12:10 GMT+09:00 pavloolenchyk <notifications@github.com>:

**Comment by dmytro** [comment]
Я бачу, що ти вже створив репозиторій на github home-work-20180128

Тепер треба створити такий же репозиторій локально:
- mkdir home-work-20180128
- cd home-work-20180128
- git init . <--- крапка в кінці
- git remote add <... alias ... > <... адреса репозиторію в github>

Попробуй розібратися, в цих командах, щоб ти зрозумів, що вони означають.



  *Dmytro Kovalov*
  http://dmytro.github.io


3 лютого 2018 р. о 14:34 Dmytro Koval'ov <dmytro.kovalov@gmail.com> написав:

**Comment by dmytro** [comment]
## Повторю тут також, щоб не загубилося:
- як ми говорили вчора, репозиторій існує в 2х варіантах,
  - локальний (на диску комп'ютера)
  - віддалений - на Github'і

Щоб мати повністю робочу конфігурацію потрібно мати їх обидва. Ти вже створив репозиторій віддалений https://github.com/pavloolenchyk/home-work-20180128. Отже, тепер залишилося сворити копію репозиторію локально і засинхронізувати їх.

### Створення локального репозиторію

```
mkdir home-work-20180128
cd home-work-20180128
git init . <--- крапка в кінці
git remote add <... alias ... > <... адреса репозиторію в github>
```

- alias: назва, "label" репозиторію. В цьому випадку буде `origin`.
- адреса: `https://github.com/pavloolenchyk/home-work-20180128`

### Синхронізувати локальний репозиторій з віддаленого

Для цього використовується команда `git pull` (Домашнє завдання №2)

### Синхронізація віддаленого репозиторію з локального

Для цього використовується команда `git push` (Домашнє завдання №3)

**Comment by pavloolenchyk** [comment]
+1. Спрацювало.

**Comment by pavloolenchyk** [comment]
А от після того git pull - ні. Що зробити?
![screenshot_33](https://user-images.githubusercontent.com/34408189/36069963-493170d2-0f35-11e8-92c9-6e06dfedc64a.png)

**Comment by dmytro** [comment]
Зверни увагу на підказку, яку видала команда: `git pull <remote> <branch>`

Ми будемо розглядати цю команду на наступному занятті, але якщо хочеш спробуй сам розібратися, скористувавшися підказкою. Замість `remote` і `branch` треба підставити конкретні назви.

**Comment by pavloolenchyk** [comment]
На занятті в класі розібралися з цим питанням.

Закрито.
