### ISSUE TITLE
Repo Watch

### ISSUE THREAD

**Issue by dmytro** [pavloolenchyk/training#2]
![image](https://user-images.githubusercontent.com/81929/35795283-0658c8ac-0a9c-11e8-8857-b0268a640b35.png)

@pavloolenchyk Щоб отримувати всі повідомлення від цього репозиторію, вмикни будь ласка слідкування за ним (watch). Як на картинці.

**Comment by pavloolenchyk** [comment]
Зроблено.

**Comment by dmytro** [comment]
👍
