### ISSUE TITLE
2. Тема git pull & git push 

### ISSUE THREAD

**Issue by dmytro** [pavloolenchyk/training#3]
##  git pull & git push 

- Використання під-команд `pull` та `push` для синхронізації змін в кількох репозиторіях. 
- Синхронізація між локальним та віддаленим. 
- Різниця між `fetch` та `pull`. 
- Параметр `--set-upstream` (`-u`)

## Документація

- `man git-pull`
- `man git-push`
- http://www.vitaliypodoba.com/2014/06/git-basics/
- [git pull українською](http://www-cs-students.stanford.edu/~blynn/gitmagic/intl/uk/ch02.html#_%D1%82%D1%80%D0%B8%D0%BC%D0%B0%D1%8E%D1%87%D0%B8_%D1%80%D1%83%D0%BA%D1%83_%D0%BD%D0%B0_%D0%BF%D1%83%D0%BB%D1%8C%D1%81%D1%96)
- [get push українською](http://www-cs-students.stanford.edu/~blynn/gitmagic/intl/uk/ch03.html#_push_%D1%87%D0%B8_pull)

**Comment by dmytro** [comment]
## Домашнє завдання

__Дано__: існуючий *локальний* репозиторій (Л1) та *віддалений* (В1) 

__Завдання__:
1. Підготовка
Клонувати *віддалений* репозиторій Л1 в іншу директорію на локальному диску. Назвемо цей новий репозиторій Л2.

2. Синхронізація локальний --> віддалений
- Додати новий файл в репозиторій Л1.
- Синхронізувати Л1 --> В1
- Перевірити, що в репозиторії В1 з'явився новий файл.

3. Синхронізація віддалений --> локальний
- Впевнитися, що в Л2 немає нового файлу
- Синхронізувати В1 --> Л2
- Перевірити, чи з'явився в Л2 новий файл.

4. Задокументувати виконані команди в коментарі, до цього завдання.

**Comment by pavloolenchyk** [comment]
Зразу не буду я пробувати, бо хочу пересвідчитись що моя відповідь нічого не взламає: 
1. git clone git@github.com:pavloolenchyk/home-work-20180128.git training
Чекаю на відповідь. Почну 2 якщо я правильно обдумав.

**Comment by dmytro** [comment]
> git clone git@github.com:pavloolenchyk/home-work-20180128.git training

Не зламає, але видасть помилку. Спробуй розібратися в чому помилка. Це з пройденого матеріалу. З того, що ми ще не вчили дам підказку: скористуйся для клонування HTTPS, а не SSH.

**Comment by pavloolenchyk** [comment]
Я думав перше що потрібно було https, а тоді передумав...Добре. Зараз попробую.

**Comment by pavloolenchyk** [comment]
Побробував https, оце сталось...Що робити?
![screenshot_46](https://user-images.githubusercontent.com/34408189/36249712-e47ce908-127e-11e8-9296-e13db65cba96.png)

**Comment by dmytro** [comment]
Прочитай уважно повідомлення про помилку: 

`destination path 'training' already exists and is not an empty directory`

Зверни увагу на:
- який репозиторій ти збираєшся клонувати?
- яка буде назва директорії (локальної)?
- Порівняй наступні дві команди. Чим вони відрізняються? Яким буде результат виконання кожної з них?
  - `git clone https://..../НАЗВА.git`
  - `git clone https://..../НАЗВА.git some_new_directory`

**Comment by pavloolenchyk** [comment]
Різниця між двома командами - факт, що перша нікуда не перепише, а просто скаже, що не вказано куда клонувати. А от друга має спрацювати, і клонувати у вказану директорію.
Зробив я нову директорію під назвою copy, побробувати клонувати знову?

**Comment by dmytro** [comment]
# Домашнє завдання

## Git pull
- Повторити вдома, те що ми робили на уроці:
  - на локальному диску в двох *різних* директоріях знаходяться 2 копії репозиторію,
  - внести зміни в одному з репозиторіїв,
  - виконати `git push` & `git pull` щоб зміни були занесені  в 2й
- Задокументувати всі кроки з виконаними командами

**Comment by dmytro** [comment]
Нагадування @pavloolenchyk - Домашнє завдання.

**Comment by pavloolenchyk** [comment]
cd training
vi readme.txt
git status
git add readme.txt
git status
git commit
git log
git diff
git push
cd ../training2
git pull

**Comment by pavloolenchyk** [comment]
git clone https://..../НАЗВА.git склонує у директорію, з тою самою назвоюю як репо.
git clone https://..../НАЗВА.git some_new_directory зробить клон у директорію з назвою some_new_directory.

**Comment by dmytro** [comment]
👍
