### ISSUE TITLE
3. Тема git add, git commit

### ISSUE THREAD

**Issue by dmytro** [pavloolenchyk/training#4]
## Дата 2018/02/18

- Поглибити знання про команду add, commit
- Команда `git diff`
- `git status`
- `git add`
- `git status --cached`
- `git commit`
- `git push`

**Comment by dmytro** [comment]
# Домашнє завдання

- Вдома ще раз внести зміни в файл readme.txt і додати ще один новий файл
  - Перевірити, що всі зміни з'явилися на github
- Задокументувати всі команди, які для цього використовувалися. Додати, як коментар до цього завдання.

**Comment by pavloolenchyk** [comment]
Зроблено. Команди:

cd training
vi readme.txt
git diff
git status
git add readme.txt
git status
git commit
git log
git push
cd ../training2
git pull
cd
Все.

**Comment by dmytro** [comment]
# Домашнє завдання (доповнення)

Якомого детальніше пояснити різницю між наступними командами `git`:
- `status`
- `diff`
- `log`

**Comment by pavloolenchyk** [comment]
# Домашнє завдання (доповнення)
git status показує статус внесків у файли у git - якщо файл виділений червоним шрифтом і каже:
`modified: example.txt`
тоді означає що ми змінили файл хоча іще не виставили на коміт. Це можна зробити через команду git add example.txt. Тоді якщо зробити git status знову, `modified: example.txt` буде виділений зеленим шрифтом.
Після того можна зробити git diff. Ця команда покаже зміни між поточним і попередній версій документа. Якщо щось було добавлено, тоді це буде видно зеленим шрифтом і з плюсиком. Якщо щось було видалено, тоді це буде червоним шривтом і з мінусиком.
Коли ми зробили git commit, тоді git log покаже нам всі коміти зроблені з інформацією что це зробив, коли, і тоді дасть специфічну цифру цьому коміту.

**Comment by dmytro** [comment]
Добре, молодець. 👍
