### ISSUE TITLE
2GB і 480Mbps

### ISSUE THREAD

**Issue by dmytro** [pavloolenchyk/training#7]
# Домашнє завдання

Скільки часу займе копіювання 2GB файлу через USB2 інтерфейс з швидкістю 480Mbps?

Завдання виконати письмово в коментарі до цієї теми. 

## Обов'язкові запитання

- Навести **повну** формулу розрахунку і пояснити числа та поняття в розрахунку. 
- Пояснити значення: 
  - слів 'біт', 'байт' та 
  - приставок 'кіло', 'меґа', 'ґіґа' (стосовно до комп'ютерних та інформаційних технологій).
- Пояснити різницю між 1000 і 1024 в розрахунках `kb`, `kB`, `Mb` тощо.
- Пояснити різницю між `Gb` та `GB`
-  В чому відмінності між `1GB` та `1Gbps`?

## Додаткове запитання

Чому в специфікаціях пристроїв пам'яті використовують велике `B` (диски, USB пам'ять, RAM), а при указанні швидкості використовується маленька `b`? 

#### Приклади
Зі сторінки  [Apple](https://www.apple.com/macbook-pro/specs/)

-----
![image](https://user-images.githubusercontent.com/81929/36941502-f3c38ace-1f9f-11e8-8010-18e4fd18eac1.png)
-----
![image](https://user-images.githubusercontent.com/81929/36941504-0001d462-1fa0-11e8-87ef-807418814fcf.png)

**Comment by pavloolenchyk** [comment]
Q# Домашнє завдання
```
1 Kb = 1024 b
1 Mb = 1 048 576 b
1 Gb = 1 073 741 824 b
1 B = 8 b
1 KB = 8192 b
1 MB = 8 388 608 b
1 GB = 8 589 934 592 b
2 GB = 17 179 869 184 b = 16384 Mb
```
**2 GB / 480 Mbps = 16384 Mb/ 480 Mbps = 34.133333 секунд щоб переписати файл на 2 гігабайти через пристрій USB 2.0.**

Біти і байти - вимір інформації які використовуются у комп'ютерах і операційних системах. 1 байт = 8 бітів.

- Кіло, мега, і гіга - префікси, які використовуются, щоб убільшити або зменшити виміри розмірів. Вони використовуются, щоб можна було легше виміряти розміри, аніж мати дуже багато нулів. Оці префікси використовуются не тільки у вазі, а іще у комп'ютерних приставках у формі бітів та байтів. Дякуючи цьому, нам легко зрозуміти скільки місця є на приставці. Проблеми з'являются коли люди купляють комп'ютер - і там вказано, що 250GB, а якщо заглянути на комп'ютер, тоді буде вказано, що 232.83 GB. Це бо комп'ютер вимірює у бінарному, і ось чому чим більший тип виміру, тим менше буде здаватись, хоча це все одно та сама сума місця.
Легче кажучи, комп'ютери вимірюють місце у бінарному способі (1024),  компанії виміриють у 1000чах щоб зробити легше для покупців, і навіть якщо дві цифри вимірів ке ті самі, всеодно означає що є та сама сума розміру.
- 1 Gb і 1 GB відрізняются у 8 раз, бо че біти і байти, і вони завжди будуть в 8 разів від один одного.
- GB (1 GigaByte) - це вимір розміру, а 1 Gbps (1 Gigabit per second) - це вимір скільки даних можна переписати  за секунду. Якщо 1 байт 8 бітів, і 1 гігабіт переписуєтся за секунду, тоді означає що оце перепишется за 8 секунд.
##Додаткове запитання
Не знаю. Для чого?

**Comment by dmytro** [comment]
Молодець. Гарна детальна відповідь. 👍 

## Пристрої пам'яті та швидкість — `B` чи `b`?

@pavloolenchyk 

Комп'ютерна пам'ять (диски чи USB пристрої) або оперативна пам'ять комп'ютера працює в основному з блоками даних. Блочний доступ до пам'яті, це коли читається або записується відразу "блок" даних. Наприклад, дискова пам'ять часто пишеться блоками по 512 байт або по 1024 байта за раз. Тому розмір цих пристроїв майже завжди вказується в **байтах** (`B`, `kB`, `MB`, `GB`).

З іншого боку пристрої зв'язку (напраклад, WiFi, Ethernet або запис/читання файла через USB)  майже завжди працює в т.зв. "потоковому" (stream) режимі. В потоковому режимі читання/запис ведеться потоком **бітів**. Тобто, щоб прочитати один байт, треба **послідовно** один за одним прочитати 8 бітів. Тому і швидкість найчастіше вказується в бітах (або `b`, `kb`, `Mb`, `Gb`)

### Додаткова інформація

Ось іще [пояснення англійською](https://lifehacker.com/the-difference-between-bits-and-bytes-and-why-it-matte-510705022) того ж самого.

**Comment by dmytro** [comment]
Молодець, гарно виконане завдання. @pavloolenchyk
